id: P010392
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC435
  title: 'མདོ་ཁམས་གནས་ཆེན་ཉེར་ལྔའི་གནས་ཡིག་ཕྱོགས་བསྒྲིགས། '
  author: ''
  volumes:
    5cc29e03ecd84cb1a6c32eb7a0ab7aa6:
      image_group_id: I2PD19779
      title: ''
      volume_number: 1
      total_pages: 608
      base_file: v001.txt
    889a15e4ece3411dbdf510002ac20162:
      image_group_id: I2PD19780
      title: ''
      volume_number: 2
      total_pages: 524
      base_file: v002.txt
